# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Schedule-Advisory
version:      1.002
version_from: lib/Schedule/Advisory.pm
installdirs:  site
requires:
    Test::Assertions:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
